### ISSUE TITLE
Usercode classes should be preferred over system-classes

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#117]
I have a Stratosphere job that has jodatime as a dependency. It seems that for our hadoop-yarn build, pact-hbase pulls jruby-complete.jar as a dependency. Jodatime is extracted into jruby-complete.
If I call a yodatime function inside my user code, the wrong (outdated) version is called, which causes an exception.

I think we need to configure the classloader in the TaskManager properly.

**Comment by rmetzger** [comment]
This commit by @AHeise https://github.com/dimalabs/ozone/commit/aca4323c1c0f05d29afcdfce5e4564663adc41e0 could fix the issue. It was merged with the maven-central deployment pull request.
I'm going to validate the fix once I'm working on that task again.

**Comment by rmetzger** [comment]
The mentioned commit by @AHeise introduces a much bigger problem, currently being in the main codeline:

```
ERROR: The job was not successfully submitted to the nephele job manager: eu.stratosphere.nephele.executiongraph.GraphConversionException: eu.stratosphere.pact.runtime.task.util.CorruptConfigurationException: Could not read the user code wrapper: java.lang.ClassNotFoundException: eu.stratosphere.tlabs.risk.input.AvroInputFormat
```

**Comment by aljoscha** [comment]
@rmetzger This is in your telekom use-case? This seems to be a problem with the move to allow objects in addition to classes for user-code. There should only be a UserCodeWrapper<AvroInputFormat> in the task config.

**Comment by rmetzger** [comment]
Stephan is on it.

**Comment by rmetzger** [comment]
Full stack

```
    at eu.stratosphere.pact.runtime.task.util.TaskConfig.getStubWrapper(TaskConfig.java:261)
    at eu.stratosphere.pact.runtime.task.RegularPactTask.instantiateUserCode(RegularPactTask.java:1311)
    at eu.stratosphere.pact.runtime.task.DataSourceTask.initInputFormat(DataSourceTask.java:289)
    at eu.stratosphere.pact.runtime.task.DataSourceTask.registerInputOutput(DataSourceTask.java:95)
    at eu.stratosphere.nephele.execution.RuntimeEnvironment.<init>(RuntimeEnvironment.java:194)
    at eu.stratosphere.nephele.executiongraph.ExecutionGroupVertex.<init>(ExecutionGroupVertex.java:236)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:497)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:275)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:176)
    at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:532)
```

**Comment by StephanEwen** [comment]
I think this issue is resolved now, no? We always load first first the user code classloader in the source tasks as well.
