### ISSUE TITLE
WordCount total ordering not working?

### ISSUE THREAD

**Issue by fpompermaier** [stratosphere/stratosphere#138]
Hi to everybody,
I tried to slightly modify the WordCount example to obtain a single output file ordered by word occurrence but I always get an error.

This is the plan of my WordCount:

``` java
@Override
public Plan getPlan(String... args) {
        // parse job parameters
        int numSubTasks   = (args.length > 0 ? Integer.parseInt(args[0]) : 1);
        String dataInput = (args.length > 1 ? args[1] : "");
        String output    = (args.length > 2 ? args[2] : "");
        FileDataSource source = new FileDataSource(new TextInputFormat(), dataInput, "Input Lines");
        // comment out this line for UTF-8 inputs
//      source.setParameter(TextInputFormat.CHARSET_NAME, "ASCII");
        MapContract mapper = MapContract.builder(new TokenizeLine())
            .input(source)
            .name("Tokenize Lines")
            .build();
        ReduceContract reducer = ReduceContract.builder(CountWords.class, PactString.class, 0)
            .input(mapper)
            .name("Count Words")
            .build();
        reducer.setDegreeOfParallelism(1);
        FileDataSink out = new FileDataSink(new RecordOutputFormat(), output, reducer, "Word Counts");
        RecordOutputFormat.configureRecordFormat(out)
            .recordDelimiter('\n')
            .fieldDelimiter(' ')
            .field(PactString.class, 0)
            .field(PactInteger.class, 1);
        // sets the group sorting to the second field
        out.setLocalOrder(new Ordering(1, PactInteger.class, Order.DESCENDING));
        Plan plan = new Plan(out, "WordCount Example");
        plan.setDefaultParallelism(numSubTasks);
        return plan;
}
```

The error I receive is:

java.lang.Exception: The data preparation for task 'Count Words' , caused an error: Invalid local strategy provided for CombineTask.
       at eu.stratosphere.pact.runtime.task.RegularPactTask.run(RegularPactTask.java:348)
       at eu.stratosphere.pact.runtime.task.RegularPactTask.invoke(RegularPactTask.java:292)
       at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:344)
       at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.RuntimeException: Invalid local strategy provided for CombineTask.
       at eu.stratosphere.pact.runtime.task.CombineDriver.prepare(CombineDriver.java:134)
       at eu.stratosphere.pact.runtime.task.RegularPactTask.run(RegularPactTask.java:343)

Best,
Flavio

**Comment by fhueske** [comment]
Flavio, thanks for reporting this bug!

That looks like a bug in the Pact compiler to me. 
The compiler should choose the correct execution strategies and something seems to go wrong here.
Will look into this issue later this evening. Maybe there's an easy fix for the problem.

Best,
Fabian

**Comment by rmetzger** [comment]
I was not able to reproduce the error. I used the wordcount in `pact-examples` and added `reducer.setDegreeOfParallelism(1);` and `out.setLocalOrder(new Ordering(1, PactInteger.class, Order.DESCENDING));`

Did you change anything else?
How did you execute your Plan? Using the LocalExecutor?

**Comment by fpompermaier** [comment]
I run the test with this:

``` java
    @Test
    public void testLocalExecutorWithWordCount() {
        try {
            // set up the files
            File inFile = new File("/tmp/myfile.json");
            File outFile = File.createTempFile("wctext", ".out");

            // run WordCount
            WordCount wc = new WordCount();
            final String inParam = "file://" + inFile.getAbsolutePath();
            final String outParam = "file://" + outFile.getAbsolutePath();

            //2 threads per CPU
            LocalExecutor.execute(wc, "16", inParam, outParam);
        } catch (Exception e) {
            e.printStackTrace();
            Assert.fail(e.getMessage());
        }

    }
```

**Comment by rmetzger** [comment]
Thank you. I was able to reproduce it.

The error only occurs with numSubTasks > 1. (But with numSubTasks = 1, the output isn't sorted ;) )

**Comment by rmetzger** [comment]
It seems that the error is caused by `reducer.setDegreeOfParallelism(1);` and a default DOP > 1.

Even though no exception occurs, the output is not sorted! So we have at least two bugs here.

**Comment by fhueske** [comment]
I found the following bugs in the Pact compiler:
1. The Pact compiler assigns the same DOP to combiners as to the corresponding reduce tasks. Instead, combiners should get the same DOP as the preceding operator by default.
2. The valid driver strategies for chained and non-chained combiners differ. Chained combiners allow only PARTIAL_GROUP. Non-chained combiners allow only SORTED_GROUP. I do not see why non-chained combiners may not be executed with the PARTIAL_GROUP strategy.

The "Invalid local strategy provided for CombineTask" error is caused, because the combiner is set to DOP 1 (same as the Reducer). As a consequence, it can no longer be chained to the mapper since only tasks with identical DOP can be chained. Finally, the exception is caused because the non-chained combiner cannot be executed with a PARTIAL_GROUP driver strategy.

@StephanEwen Please comment my observations. Did I miss something or should those two things be changed?

Finally, I do not think that sorted output is supported yet. At least I haven't seen support for that in the code and the generated execution plan. We should throw an "Unsupported" exception whenever a user tries to use this "feature" in a job until it is implemented.

**Comment by fhueske** [comment]
I just issued a pull request to fix the issues with the combine task.
However, this does not solve the non-working sorted output. See #146

**Comment by StephanEwen** [comment]
Local ordering should be working now. Global ordering requires the range-partitioner and histogram builder to be forward fitted.

**Comment by StephanEwen** [comment]
Preconditions for this fix are #7 and #8.
