### ISSUE TITLE
Map after BulkIteration does not work

### ISSUE THREAD

**Issue by aljoscha** [stratosphere/stratosphere#212]
This is the exception I get:
eu.stratosphere.pact.compiler.CompilerException: An error occurred while translating the optimized plan to a nephele JobGraph: null
    at eu.stratosphere.pact.compiler.plantranslate.NepheleJobGraphGenerator.postVisit(NepheleJobGraphGenerator.java:556)
    at eu.stratosphere.pact.compiler.plantranslate.NepheleJobGraphGenerator.postVisit(NepheleJobGraphGenerator.java:1)
    at eu.stratosphere.pact.compiler.plan.candidate.SingleInputPlanNode.accept(SingleInputPlanNode.java:142)
    at eu.stratosphere.pact.compiler.plan.candidate.SingleInputPlanNode.accept(SingleInputPlanNode.java:141)
    at eu.stratosphere.pact.compiler.plan.candidate.OptimizedPlan.accept(OptimizedPlan.java:161)
    at eu.stratosphere.pact.compiler.plantranslate.NepheleJobGraphGenerator.compileJobGraph(NepheleJobGraphGenerator.java:165)
    at eu.stratosphere.pact.test.util.TestBase2.getJobGraph(TestBase2.java:282)

@StephanEwen this could also have to to with the mapper chaining I suppose?

Also, when I use the output of an iteration in a file sink and also as one input of a match I get the same exception. Maybe thats related, maybe not.

**Comment by StephanEwen** [comment]
We cannot chain to iterations nodes. This is a one line fix, I'll get onto it...

**Comment by StephanEwen** [comment]
31dbfe65e46d8419d0da8d670b5958407adbdbf2 fixes the mapper chaining issue.

I'll look into the case where the iteration result has two consumers...

**Comment by StephanEwen** [comment]
@aljoscha Do you have a minimal test case for that?

**Comment by aljoscha** [comment]
I think we can close this, right? And the other thing is also fixed.

**Comment by StephanEwen** [comment]
Okay, close it if your problem is solved. I am adding a test case for the case of an iteration followed by a multiple consumers.

**Comment by StephanEwen** [comment]
Fixed in d1498502482d4e5045880c21a8e5b4fab2caa1b4
