### ISSUE TITLE
Automatic hardware extraction unstable

### ISSUE THREAD

**Issue by AHeise** [stratosphere/stratosphere#216]
Occasionally, the hardware inference of Nephele does not work as expected. As can be seen in the following excerpt, sometimes too few free memory is assumed and thus the memory manager fails to initialize.
This error cannot be reproduced by running a single test, so that I suspect that prior tests fills the memory with short-lived objects, but not full enough for the garbage collector to run. This is indicated by the first line in the log (max is actually the difference). In general, free memory in Java seems to be a bad indicator on how much memory is actually available.

<pre>
13/10/24 16:14:14 INFO instance.HardwareDescriptionFactory: Found Tenured Gen pool (max: 16576, used: 357941056)
13/10/24 16:14:14 INFO taskmanager.TaskManager: Initializing memory manager with 0 megabytes of memory
13/10/24 16:14:14 FATAL taskmanager.TaskManager: Unable to initialize memory manager with 0 megabytes of memory
java.lang.IllegalArgumentException: The given amount of memory amounted to less than one page.
    at eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager.<init>(DefaultMemoryManager.java:133)
    at eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager.<init>(DefaultMemoryManager.java:100)
    at eu.stratosphere.nephele.taskmanager.TaskManager.<init>(TaskManager.java:289)
    at eu.stratosphere.nephele.instance.local.LocalTaskManagerThread.<init>(LocalTaskManagerThread.java:40)
    at eu.stratosphere.nephele.instance.local.LocalInstanceManager.<init>(LocalInstanceManager.java:143)
    at eu.stratosphere.nephele.jobmanager.JobManager.<init>(JobManager.java:226)
    at eu.stratosphere.pact.client.minicluster.NepheleMiniCluster.start(NepheleMiniCluster.java:164)
    at eu.stratosphere.sopremo.server.SopremoTestServer.<init>(SopremoTestServer.java:75)
    at eu.stratosphere.sopremo.server.SopremoServerIT.setup(SopremoServerIT.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
    at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
    at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
13/10/24 16:14:14 FATAL jobmanager.JobManager: Cannot instantiate local instance manager: java.lang.RuntimeException: java.lang.IllegalArgumentException: The given amount of memory amounted to less than one page.
    at eu.stratosphere.nephele.instance.local.LocalTaskManagerThread.<init>(LocalTaskManagerThread.java:42)
    at eu.stratosphere.nephele.instance.local.LocalInstanceManager.<init>(LocalInstanceManager.java:143)
    at eu.stratosphere.nephele.jobmanager.JobManager.<init>(JobManager.java:226)
    at eu.stratosphere.pact.client.minicluster.NepheleMiniCluster.start(NepheleMiniCluster.java:164)
    at eu.stratosphere.sopremo.server.SopremoTestServer.<init>(SopremoTestServer.java:75)
    at eu.stratosphere.sopremo.server.SopremoServerIT.setup(SopremoServerIT.java:58)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
    at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
    at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
Caused by: java.lang.IllegalArgumentException: The given amount of memory amounted to less than one page.
    at eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager.<init>(DefaultMemoryManager.java:133)
    at eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager.<init>(DefaultMemoryManager.java:100)
    at eu.stratosphere.nephele.taskmanager.TaskManager.<init>(TaskManager.java:289)
    at eu.stratosphere.nephele.instance.local.LocalTaskManagerThread.<init>(LocalTaskManagerThread.java:40)
    ... 33 more
</pre>

(full log at  https://s3.amazonaws.com/archive.travis-ci.org/jobs/12992423/log.txt )

**Comment by rmetzger** [comment]
Does it make sense to call `System.gc()` before determining the free memory?

We should also fix the TODO there in the code.

**Comment by AHeise** [comment]
No, System.gc() is only a hint. Also with Java 7 and its concurrent GC, I doubt that this method would ever block.

http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#gc%28%29

There are a couple of suggestions (aka Hacks) around, but basically you can never really estimate sufficiently enough how much main memory is left. I would rather suggest to take a percentage of overall memory instead of free memory. You could also make that percentage configurable. (I know that you can already configure the absolute number, however these errors occur mainly on CI VMs and I have not figured out how much RAM they have and even if they have the same amount at all).

**Comment by rmetzger** [comment]
Assigned to @markus-h

**Comment by StephanEwen** [comment]
Fixed in 945a3c6e0a9533f2f3f0f115c2ac52f4e8c0d9c0
