### ISSUE TITLE
Compile errors in the stratosphere-quickstart archetype

### ISSUE THREAD

**Issue by aalexandrov** [stratosphere/stratosphere#267]
I get the following two errors on a freshly created scala quickstart archetype. 

First error occurs at line 2

```
import scala.Array.canBuildFrom
```

and says "object Array is not a member of package eu.stratosphere.scala".

Second error is at line 91

```
val words = input flatMap { _.toLowerCase().split("""\W+""") filter { _ != "" } map { (_, 1) } }
```

and says 

```
scala.reflect.macros.TypecheckException: object Array is not a member of package eu.stratosphere.scala
    at scala.reflect.macros.runtime.Typers$$anonfun$typeCheck$2.apply(Typers.scala:31)
    at scala.reflect.macros.runtime.Typers$$anonfun$typeCheck$2.apply(Typers.scala:25)
    at scala.tools.nsc.typechecker.Contexts$Context.withMacrosEnabled(Contexts.scala:242)
    at scala.reflect.macros.runtime.Typers$$anonfun$3.apply(Typers.scala:18)
    at scala.reflect.macros.runtime.Typers$$anonfun$3.apply(Typers.scala:18)
    at scala.reflect.macros.runtime.Typers$$anonfun$wrapper$1$1.apply(Typers.scala:19)
    at scala.reflect.macros.runtime.Typers$$anonfun$wrapper$1$1.apply(Typers.scala:19)
    at scala.tools.nsc.typechecker.Contexts$Context.withImplicitsEnabled(Contexts.scala:211)
    at scala.reflect.macros.runtime.Typers$$anonfun$1.apply(Typers.scala:17)
    at scala.reflect.macros.runtime.Typers$$anonfun$1.apply(Typers.scala:17)
    at scala.reflect.macros.runtime.Typers$class.wrapper$1(Typers.scala:19)
    at scala.reflect.macros.runtime.Typers$class.typeCheck(Typers.scala:25)
    at scala.reflect.macros.runtime.Context.typeCheck(Context.scala:6)
    at scala.reflect.macros.runtime.Context.typeCheck(Context.scala:6)
    at eu.stratosphere.scala.codegen.TreeGen$class.typeCheck(TreeGen.scala:184)
    at eu.stratosphere.scala.codegen.MacroContextHolder$$anon$1.typeCheck(MacroContextHolder.scala:21)
    at eu.stratosphere.scala.codegen.UDTGen$class.mkUdtClass(UDTGen.scala:37)
    at eu.stratosphere.scala.codegen.MacroContextHolder$$anon$1.mkUdtClass(MacroContextHolder.scala:21)
    at eu.stratosphere.scala.operators.MapMacros$.flatMap(MapOperator.scala:105)
```

Seems like the `scala.Array.canBuildFrom` import is not properly resolved.

**Comment by aljoscha** [comment]
I updated the quickstart to make it work with the latest stratosphere version.

**Comment by rmetzger** [comment]
Did you test it?

I'm still getting

```
$ mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Your Job's Name 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- build-helper-maven-plugin:1.7:add-source (add-source) @ stratosphere-project ---
[INFO] Source directory: /home/robert/Projekte/t-labs/bdaw.usecases/risk/tuberlin/verify-results/src/main/scala added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ stratosphere-project ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/robert/Projekte/t-labs/bdaw.usecases/risk/tuberlin/verify-results/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ stratosphere-project ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.1.4:compile (default) @ stratosphere-project ---
[INFO] /home/robert/Projekte/t-labs/bdaw.usecases/risk/tuberlin/verify-results/src/main/scala:-1: info: compiling
[INFO] Compiling 1 source files to /home/robert/Projekte/t-labs/bdaw.usecases/risk/tuberlin/verify-results/target/classes at 1384197548509
[ERROR] /home/robert/Projekte/t-labs/bdaw.usecases/risk/tuberlin/verify-results/src/main/scala/eu/stratosphere/quickstart/Job.scala:83: error: object eu.stratosphere.pact.common.io.DelimitedOutputFormat is not a value
[ERROR]     val output = counts.write(wordsOutput, DelimitedOutputFormat(formatOutput.tupled))
[ERROR]                                            ^
[ERROR] one error found
```

BTW: I actually wanted to test if its possible to write a little scala job within 5 minutes. Seems like the test already failed.

**Comment by aljoscha** [comment]
I just did a:

``` bash
curl https://raw.github.com/stratosphere/stratosphere-quickstart/master/quickstart-scala.sh | bash
cd quickstart
mvn package
mvn exec:exec -Dexec.executable="java" -Dexec.args="-cp %classpath eu.stratosphere.quickstart.RunJobLocal 2 file:///home/aljoscha/unison.log file:///home/aljoscha/wc-out"
```

It worked just like that.

**Comment by rmetzger** [comment]
Okay, sorry. Seems that there is something wrong with my eclipse here? You're right, its working: http://showterm.io/a354d7e71755184bdd406

**Comment by aljoscha** [comment]
IntelliJ for the win... :+1:
