### ISSUE TITLE
NullPointerException in MutableHashTable on cancelling Task

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#281]
Today, I got this NPE.
The job has a Match and a Reduce. The Match failed due to a (usercode) runtime exception. During the cancellation of the whole job, the following NPE occurred:

```
14:19:08,130 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from CANCELING to CANCELED for task Match on string key (6/64)
14:19:08,134 ERROR eu.stratosphere.nephele.taskmanager.runtime.RuntimeTask       - java.lang.NullPointerException
        at eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager.release(DefaultMemoryManager.java:337)
        at eu.stratosphere.pact.runtime.hash.BuildFirstHashMatchIterator.abort(BuildFirstHashMatchIterator.java:171)
        at eu.stratosphere.pact.runtime.task.MatchDriver.cancel(MatchDriver.java:185)
        at eu.stratosphere.pact.runtime.task.RegularPactTask.cancel(RegularPactTask.java:416)
        at eu.stratosphere.nephele.taskmanager.runtime.RuntimeTask.cancelOrKillExecution(RuntimeTask.java:227)
        at eu.stratosphere.nephele.taskmanager.runtime.RuntimeTask.cancelExecution(RuntimeTask.java:186)
        at eu.stratosphere.nephele.taskmanager.TaskManager$1.run(TaskManager.java:399)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:679)

14:19:08,136 WARN  eu.stratosphere.pact.runtime.task.RegularPactTask             - PACT code cancelled.: Match on string key (13/64)
```

The `availableMemory` of the HashMap seem to contain `null` memory segments.

(See also https://github.com/stratosphere/stratosphere/issues/154#issuecomment-29071859)

**Comment by StephanEwen** [comment]
The problem was that the cancel call on the hash join started releasing memory. The regular cleanup code also releases the memory. Segments cannot be double released, but obtaining the reference to them may fail in race conditions.

Logic is not that canceling only breaks the operating loops and memory release happens only in the operator cleanup parts.

7b0c53b4c501690866523468f6c3e7f06438658c
