### ISSUE TITLE
GraphConversionException: Job and execution vertex * have different number of inputs

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#282]
This is a job I want to execute: https://github.com/rmetzger/scratch/blob/eda1e1432f104d81e6ae3fcb7657a24b163e5d75/src/main/java/eu/stratosphere/FlexCmp.java

Either the error message is not helpful or there is a bug with the pact-compiler?

```
13/11/22 19:49:43 ERROR client.JobClient: ERROR: eu.stratosphere.nephele.executiongraph.GraphConversionException: Job and execution vertex Write stats have different number of inputs
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createInitialGroupEdges(ExecutionGraph.java:409)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:282)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:176)
    at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:534)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
    at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:946)
```

The error only occurs if the FileDataSink statsOut has more than one input files.

**Comment by rmetzger** [comment]
Ah, okay, the issue has already been reported here: https://github.com/stratosphere/stratosphere/issues/112
