### ISSUE TITLE
LocalDistributedExecutor startup fails with single TaskManager

### ISSUE THREAD

**Issue by uce** [stratosphere/stratosphere#480]
When I start the `LocalDistributedExecutor` with just a single TaskManager, the startup fails, e.g. changing line 46 from `lde.start(2);` to `lde.start(1);` in [LocalDistributedExecutorTest](https://github.com/stratosphere/stratosphere/blob/master/stratosphere-tests/src/test/java/eu/stratosphere/test/localDistributed/LocalDistributedExecutorTest.java?source=cc) does not work.

**Comment by rmetzger** [comment]
Recently, the LDE test failed on travis: https://travis-ci.org/stratosphere/stratosphere/jobs/19119983

```
Running eu.stratosphere.test.localDistributed.LocalDistributedExecutorTest
16:29:32,678 ERROR eu.stratosphere.nephele.jobmanager.JobManager                 - Cannot start RPC server: java.net.BindException: Problem binding to localhost/127.0.0.1:6498 : Address already in use
    at eu.stratosphere.nephele.ipc.Server.bind(Server.java:198)
    at eu.stratosphere.nephele.ipc.Server$Listener.<init>(Server.java:272)
    at eu.stratosphere.nephele.ipc.Server.<init>(Server.java:994)
    at eu.stratosphere.nephele.ipc.RPC$Server.<init>(RPC.java:402)
    at eu.stratosphere.nephele.ipc.RPC.getServer(RPC.java:355)
    at eu.stratosphere.nephele.jobmanager.JobManager.<init>(JobManager.java:236)
    at eu.stratosphere.client.localDistributed.LocalDistributedExecutor.start(LocalDistributedExecutor.java:93)
    at eu.stratosphere.test.localDistributed.LocalDistributedExecutorTest.testLocalDistributedExecutorWithWordCount(LocalDistributedExecutorTest.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:104)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:147)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:101)
    at com.sun.proxy.$Proxy0.invoke(Unknown Source)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:139)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:82)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:81)
Caused by: java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:444)
    at sun.nio.ch.Net.bind(Net.java:436)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at eu.stratosphere.nephele.ipc.Server.bind(Server.java:196)
    ... 35 more
```

**Comment by StephanEwen** [comment]
I have seen this also, but could not reproduce it. seems like multiple
jobmanager instances get started.

Do you run more than one test with the DistributedExecutor in the same JVM?
If so, you may see that the previous one has not fully shut down before the
next one starts. Particularly, the RPC threads linger...
