### ISSUE TITLE
HDFS access with YARN fails reproducible, but only on the first access

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#584]
I'm sill working on https://github.com/stratosphere/stratosphere/issues/568 and there is a weird issue.

Once the YARN session came up, the system is unable to open the file input splits (dop=16, tm = 1, JM/TM on different machines).

The exception is thrown by the `InputSplitOpenThread`. The line in the FileSytem code is nothing special. I don't see any reason to timeout there.

```
03/15/2014 13:17:55:    Job execution switched to status FAILED
ERROR: The program execution failed: java.io.IOException: Error opening the Input Split hdfs://master.local:9000/input [26364,2197]: Input opening request timed out. Opener was  alive. Stack:
    at eu.stratosphere.core.fs.FileSystem.get(FileSystem.java:197)
    at eu.stratosphere.api.common.io.FileInputFormat$InputSplitOpenThread.run(FileInputFormat.java:687)

    at eu.stratosphere.api.common.io.FileInputFormat.open(FileInputFormat.java:550)
    at eu.stratosphere.api.common.io.DelimitedInputFormat.open(DelimitedInputFormat.java:415)
    at eu.stratosphere.api.common.io.DelimitedInputFormat.open(DelimitedInputFormat.java:44)
    at eu.stratosphere.pact.runtime.task.DataSourceTask.invoke(DataSourceTask.java:134)
    at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:345)
    at java.lang.Thread.run(Thread.java:701)
Caused by: java.io.IOException: Input opening request timed out. Opener was  alive. Stack:
    at eu.stratosphere.core.fs.FileSystem.get(FileSystem.java:197)
    at eu.stratosphere.api.common.io.FileInputFormat$InputSplitOpenThread.run(FileInputFormat.java:687)

    at eu.stratosphere.api.common.io.FileInputFormat$InputSplitOpenThread.waitForCompletion(FileInputFormat.java:738)
    at eu.stratosphere.api.common.io.FileInputFormat.open(FileInputFormat.java:547)
    ... 5 more
```

Any ideas?

**Comment by StephanEwen** [comment]
Normally, the timeout is not set (or set to inifinite) in the stratosphere
configuration (see reference documentation on the homepage). Do you use a
configuration where you manually set that value?

**Comment by rmetzger** [comment]
The timeout mechanism is not really working.
I have to do some more debugging, but the value is set to Long.MAX_VALUE.

The problem is that the timeout is evaluated in this statement
`remaining = this.timeout + start - System.currentTimeMillis()) > 0`
If this.timeout == Long.MAX_VALUE, we'll have a overflow here (start is always > 1).

I'm getting different exceptions: (and the error does not always occur ofter I started the YARN session. Only sometimes.)
I suspect one thing: I have a vagrant setup with 4 virtual machines. The hostname resolution works via zeroconf (avahi). If I access the virtual hosts from the physical host, the resolution sometimes takes more than 5 seconds. This might be the reason for the error.
But I'll certainly look into the InputSplitOpenThread class to check that the timeout is working correctly.

```
java.io.IOException: Error opening the Input Split hdfs://master.local:9000/input [10985,2197]: Input opening request timed out. Opener was  alive. Stack:
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:290)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:286)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:286)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:763)
        at eu.stratosphere.runtime.fs.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:342)
        at eu.stratosphere.api.common.io.FileInputFormat$InputSplitOpenThread.run(FileInputFormat.java:688)

        at eu.stratosphere.api.common.io.FileInputFormat.open(FileInputFormat.java:550)
        at eu.stratosphere.api.common.io.DelimitedInputFormat.open(DelimitedInputFormat.java:415)
        at eu.stratosphere.api.common.io.DelimitedInputFormat.open(DelimitedInputFormat.java:44)
        at eu.stratosphere.pact.runtime.task.DataSourceTask.invoke(DataSourceTask.java:134)
        at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:345)
        at java.lang.Thread.run(Thread.java:701)
Caused by: java.io.IOException: Input opening request timed out. Opener was  alive. Stack:
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:290)
        at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:286)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:286)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:763)
        at eu.stratosphere.runtime.fs.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:342)
        at eu.stratosphere.api.common.io.FileInputFormat$InputSplitOpenThread.run(FileInputFormat.java:688)

        at eu.stratosphere.api.common.io.FileInputFormat$InputSplitOpenThread.waitForCompletion(FileInputFormat.java:738)
        at eu.stratosphere.api.common.io.FileInputFormat.open(FileInputFormat.java:547)
        ... 5 more
```

**Comment by rmetzger** [comment]
Damn. The DelimitedInputFormat.getStatistics() method is setting the timeout to 10000 without setting it back to its "old" value.
