### ISSUE TITLE
Check at job compile time that CSVOutputFormat works only on DataSet<Tuple>

### ISSUE THREAD

**Issue by fhueske** [stratosphere/stratosphere#620]
Currently, the system will start executing the job and fail with an exception similar to this one: 

```
17:44:25,011 ERROR eu.stratosphere.pact.runtime.task.DataSinkTask                - Error in Pact user code: java.lang.String cannot be cast to eu.stratosphere.api.java.tuple.Tuple:  DataSink(eu.stratosphere.api.java.io.CsvOutputFormat@4f902864) (2/4)
java.lang.ClassCastException: java.lang.String cannot be cast to eu.stratosphere.api.java.tuple.Tuple
    at eu.stratosphere.api.java.io.CsvOutputFormat.writeRecord(CsvOutputFormat.java:31)
    at eu.stratosphere.pact.runtime.task.DataSinkTask.invoke(DataSinkTask.java:170)
    at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:345)
    at java.lang.Thread.run(Thread.java:744)
17:44:25,021 ERROR eu.stratosphere.nephele.taskmanager.runtime.RuntimeTask       - java.lang.ClassCastException: java.lang.String cannot be cast to eu.stratosphere.api.java.tuple.Tuple
    at eu.stratosphere.api.java.io.CsvOutputFormat.writeRecord(CsvOutputFormat.java:31)
    at eu.stratosphere.pact.runtime.task.DataSinkTask.invoke(DataSinkTask.java:170)
    at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:345)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by StephanEwen** [comment]
Fixed as part of 3b3260a6d7013fc8afb4fa9ac9744205aed50f81 (line 204)
