### ISSUE TITLE
Runtime Exception when shuffling large Records

### ISSUE THREAD

**Issue by mleich** [stratosphere/stratosphere#652]
Hi,

I have a job that reads (sometimes) large web documents from HBase and performs entity extraction in those docs.
Between the HBase source and the NER Mapper I randomly shuffle the records to different mapper to compensate for skew in the data.

``` Java
mapper.setParameter("INPUT_SHIP_STRATEGY", "SHIP_REPARTITION");
```

Look here for details: https://groups.google.com/forum/#!topic/stratosphere-users/pIw0eyMkLd8

I'm fairly sure the issue is caused by the records being large and by shuffling them over the network in the fist place because:
1. the problem didn't occur when the source and NER mapper were chained
2. the problem didn't occur when I enabled shuffling but accidentally omitted the document content which made for very small records
3. the exception says so, duh!

```
eu.stratosphere.client.program.ProgramInvocationException: The program execution failed: java.io.IOException: An error occurred in the channel: Expected data packet 82 but received 84
        at eu.stratosphere.nephele.io.channels.bytebuffered.AbstractByteBufferedInputChannel.isClosed(AbstractByteBufferedInputChannel.java:149)
        at eu.stratosphere.nephele.io.channels.bytebuffered.AbstractByteBufferedInputChannel.readRecord(AbstractByteBufferedInputChannel.java:92)
        at eu.stratosphere.nephele.io.RuntimeInputGate.readRecord(RuntimeInputGate.java:192)
        at eu.stratosphere.nephele.io.MutableRecordReader.next(MutableRecordReader.java:78)
        at eu.stratosphere.pact.runtime.task.util.RecordReaderIterator.next(RecordReaderIterator.java:41)
        at eu.stratosphere.pact.runtime.task.util.RecordReaderIterator.next(RecordReaderIterator.java:25)
        at eu.stratosphere.pact.runtime.task.MapDriver.run(MapDriver.java:79)
        at eu.stratosphere.pact.runtime.task.RegularPactTask.run(RegularPactTask.java:403)
        at eu.stratosphere.pact.runtime.task.RegularPactTask.invoke(RegularPactTask.java:294)
        at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:342)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Expected data packet 82 but received 84
        at eu.stratosphere.nephele.taskmanager.runtime.RuntimeInputChannelContext.queueTransferEnvelope(RuntimeInputChannelContext.java:147)
        at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelopeWithBuffer(ByteBufferedChannelManager.java:363)
        at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelope(ByteBufferedChannelManager.java:329)
        at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelopeFromNetwork(ByteBufferedChannelManager.java:636)
        at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnection.read(IncomingConnection.java:98)
        at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnectionThread.doRead(IncomingConnectionThread.java:185)
        at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnectionThread.run(IncomingConnectionThread.java:124)

        at eu.stratosphere.client.program.Client.run(Client.java:338)
        at eu.stratosphere.client.program.Client.run(Client.java:282)
        at eu.stratosphere.client.program.Client.run(Client.java:250)
        at eu.stratosphere.client.RemoteExecutor.executePlan(RemoteExecutor.java:84)
        at org.okkam.dopa.ner.ImrNerTaskDriver.runNerTask(ImrNerTaskDriver.java:65)
        at org.okkam.dopa.ner.ImrNerTaskDriver.main(ImrNerTaskDriver.java:150)
```

**Comment by uce** [comment]
Indeed, it seems to be a problem with the network stack.

We reworked large parts of the network stack, but didn't merge it yet. While doing this, I experienced the same problem of missing/skipped envelopes when sending out empty buffers and fixed the problem in the reworked version.

Can you checkout out the my [netstack_rework branch](https://github.com/uce/stratosphere/tree/netstack_rework) and report if it is working with it? It is not based on the newest snapshot version, but I hope that it will be OK for your program.

Please let me know, if your program doesn't work with the Stratosphere version of the branch or the problem still exists there.

**Comment by mleich** [comment]
Thanks @uce, good to know it's on the radar.
In the meantime I pushed down some simple filters we had in our program anyways. Turns the large documents that caused to issue should have been pruned anyways.

Time on this specific cluster with this dataset is limited, I'll try to come up with some minimal code snippet so we can reproduce the issue in any other environment.

**Comment by mleich** [comment]
It turns out that pruning certain large records doesn't fix the problem.
So I tested the branch form @uce, unfortunately, the issue still persists.

```
j20:13:48,616 INFO  eu.stratosphere.nephele.client.JobClient                      - 04/02/2014 20:13:46: CHAIN Map (Run NER) -> Combine(Group Entities) (8/16) switched to FAILED
java.io.IOException: An error occurred in the channel: Expected data packet 24 but received 27
        at eu.stratosphere.runtime.io.channels.InputChannel.isClosed(InputChannel.java:233)
        at eu.stratosphere.runtime.io.channels.InputChannel.readRecord(InputChannel.java:163)
        at eu.stratosphere.runtime.io.gates.InputGate.readRecord(InputGate.java:237)
        at eu.stratosphere.runtime.io.api.MutableRecordReader.next(MutableRecordReader.java:79)
        at eu.stratosphere.pact.runtime.task.util.RecordReaderIterator.next(RecordReaderIterator.java:41)
        at eu.stratosphere.pact.runtime.task.util.RecordReaderIterator.next(RecordReaderIterator.java:25)
        at eu.stratosphere.pact.runtime.task.CollectorMapDriver.run(CollectorMapDriver.java:77)
        at eu.stratosphere.pact.runtime.task.RegularPactTask.run(RegularPactTask.java:503)
        at eu.stratosphere.pact.runtime.task.RegularPactTask.invoke(RegularPactTask.java:371)
        at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:312)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.io.IOException: Expected data packet 24 but received 27
        at eu.stratosphere.runtime.io.channels.InputChannel.queueEnvelope(InputChannel.java:333)
        at eu.stratosphere.runtime.io.network.ChannelManager.dispatchFromNetwork(ChannelManager.java:566)
        at eu.stratosphere.runtime.io.network.tcp.IncomingConnection.read(IncomingConnection.java:62)
        at eu.stratosphere.runtime.io.network.tcp.IncomingConnectionThread.doRead(IncomingConnectionThread.java:188)
        at eu.stratosphere.runtime.io.network.tcp.IncomingConnectionThread.run(IncomingConnectionThread.java:121)
```

**Comment by StephanEwen** [comment]
Okay, that's unfortunate. Is it by any chance deterministic, does it always
occur between packets 24 and 27 when you re-run the job?

**Comment by mleich** [comment]
Not between the same packets, but more or less in the same timeframe (in the first three minutes):

```
20:11:14,462 scheduled -> 20:13:48,616 ... 24 but received 27
20:33:30,578 scheduled -> 20:35:46,786 ... 22 but received 28
20:37:04,263 scheduled -> 20:39:18,382 ... 9 but received 10
```

**Comment by uce** [comment]
Will you have time to extract a minimal code snippet with some sample data soon? It's crucial that we fix this.

Btw: How large are the documents/records? I could also try to reproduce the problem.

**Comment by mleich** [comment]
I did some more testing
I have 8 nodes and used a DOP of 1, 2, 4, 8, 16, 32.
For dop >= 4 the error occurred within the first 3 minutes.
For dop < 4 I stopped execution after 6-10 minutes, the error didn't occur so far. I assume  that a certain HBase region in the input splits generates a sequence of records that is large enough.

Running the the locally with DOP 4 didn't reproduce the issue.I'm trying to build the minimal snippet now.

**Comment by uce** [comment]
Ok, thank you!

You could also try to run it locally with the LocalDistributedExecutor (I suggest to look into the LocalDistributedExecutorITCase to see how it's used), which will also use the TCP stack locally instead of just the in-memory channels.

**Comment by mleich** [comment]
I managed to make most of my cluster nodes unresponsive, have to wait until the admin fixes them again.
So far my test doesn't reproduce the issue.
Must be some strange mixture of varying records sizes and record inter arrival times.
Going to continue tomorrow.

**Comment by rmetzger** [comment]
Just FYI, I am able to reproduce this error on the 26 node DIMA cluster with the large test job. (However, it takes around 4 hours)

```
Error: java.io.IOException: An error occurred in the channel: Expected data packet 8 but received 9
at eu.stratosphere.nephele.io.channels.bytebuffered.AbstractByteBufferedInputChannel.isClosed(AbstractByteBufferedInputChannel.java:149)
at eu.stratosphere.nephele.io.channels.bytebuffered.AbstractByteBufferedInputChannel.readRecord(AbstractByteBufferedInputChannel.java:92)
at eu.stratosphere.nephele.io.RuntimeInputGate.readRecord(RuntimeInputGate.java:192)
at eu.stratosphere.nephele.io.MutableRecordReader.next(MutableRecordReader.java:78)
at eu.stratosphere.pact.runtime.task.util.RecordReaderIterator.next(RecordReaderIterator.java:41)
at eu.stratosphere.pact.runtime.task.util.RecordReaderIterator.next(RecordReaderIterator.java:25)
at eu.stratosphere.pact.runtime.resettable.SpillingResettableMutableObjectIterator.next(SpillingResettableMutableObjectIterator.java:144)
at eu.stratosphere.pact.runtime.task.CrossDriver.runBlockedOuterFirst(CrossDriver.java:212)
at eu.stratosphere.pact.runtime.task.CrossDriver.run(CrossDriver.java:146)
at eu.stratosphere.pact.runtime.task.RegularPactTask.run(RegularPactTask.java:511)
at eu.stratosphere.pact.runtime.task.RegularPactTask.invoke(RegularPactTask.java:376)
at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:351)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Expected data packet 8 but received 9
at eu.stratosphere.nephele.taskmanager.runtime.RuntimeInputChannelContext.queueTransferEnvelope(RuntimeInputChannelContext.java:147)
at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelopeWithBuffer(ByteBufferedChannelManager.java:364)
at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelope(ByteBufferedChannelManager.java:330)
at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelopeFromNetwork(ByteBufferedChannelManager.java:637)
at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnection.read(IncomingConnection.java:98)
at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnectionThread.doRead(IncomingConnectionThread.java:185)
at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnectionThread.run(IncomingConnectionThread.java:124)
```

**Comment by rmetzger** [comment]
In 0.5-rc3, the error occurs almost instantly with the large testjob

```
05/29/2014 10:59:10:    Job execution switched to status FAILED
Error: The program execution failed: java.lang.Exception: The data preparation for task 'Join(T4 Join: All order keys)' , caused an error: An error occurred creating the temp table.
    at eu.stratosphere.pact.runtime.task.RegularPactTask.run(RegularPactTask.java:483)
    at eu.stratosphere.pact.runtime.task.RegularPactTask.invoke(RegularPactTask.java:373)
    at eu.stratosphere.nephele.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:351)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: An error occurred creating the temp table.
    at eu.stratosphere.pact.runtime.task.TempBarrier.getIterator(TempBarrier.java:92)
    at eu.stratosphere.pact.runtime.task.RegularPactTask.getInput(RegularPactTask.java:1122)
    at eu.stratosphere.pact.runtime.task.MatchDriver.prepare(MatchDriver.java:93)
    at eu.stratosphere.pact.runtime.task.RegularPactTask.run(RegularPactTask.java:478)
    ... 3 more
Caused by: java.io.IOException: An error occurred in the channel: Expected data packet 0 but received 1
    at eu.stratosphere.nephele.io.channels.bytebuffered.AbstractByteBufferedInputChannel.isClosed(AbstractByteBufferedInputChannel.java:149)
    at eu.stratosphere.nephele.io.channels.bytebuffered.AbstractByteBufferedInputChannel.readRecord(AbstractByteBufferedInputChannel.java:92)
    at eu.stratosphere.nephele.io.RuntimeInputGate.readRecord(RuntimeInputGate.java:192)
    at eu.stratosphere.nephele.io.MutableRecordReader.next(MutableRecordReader.java:78)
    at eu.stratosphere.pact.runtime.task.util.RecordReaderIterator.next(RecordReaderIterator.java:41)
    at eu.stratosphere.pact.runtime.task.util.RecordReaderIterator.next(RecordReaderIterator.java:25)
    at eu.stratosphere.pact.runtime.task.TempBarrier$TempWritingThread.run(TempBarrier.java:171)
Caused by: java.io.IOException: Expected data packet 0 but received 1
    at eu.stratosphere.nephele.taskmanager.runtime.RuntimeInputChannelContext.queueTransferEnvelope(RuntimeInputChannelContext.java:147)
    at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelopeEnvelopeWithoutBuffer(ByteBufferedChannelManager.java:447)
    at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelope(ByteBufferedChannelManager.java:328)
    at eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager.processEnvelopeFromNetwork(ByteBufferedChannelManager.java:637)
    at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnection.read(IncomingConnection.java:96)
    at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnectionThread.doRead(IncomingConnectionThread.java:185)
    at eu.stratosphere.nephele.taskmanager.bytebuffered.IncomingConnectionThread.run(IncomingConnectionThread.java:124)
```
