### ISSUE TITLE
KMeans Scala example does not work with Quick Start

### ISSUE THREAD

**Issue by aalexandrov** [stratosphere/stratosphere#870]
The KMeans Scala and Java examples differ in the expected input format - the Scala program expects `(pointID, x, y, z)` as input whereas the Java program expects `(x, y)`, which is the format generated by the `KMeansDataGenerator`.

Consequently, the [Quick Start](http://stratosphere.eu/quickstart/example.html) seems to work only with the Java example.

**Comment by aalexandrov** [comment]
I'm working on a fix.

**Comment by fhueske** [comment]
Will you adapt the Scala version? 
I have also an updated version of the Python script which works for the Java example.

**Comment by aalexandrov** [comment]
Yes, I adapted the Scala version in PR #873. I also have modified the Python script so one can plot the input (unclustered points with one color), as well as the output (clustered points, each cluster with distinct color):

``` python
#!/usr/bin/python
import sys
import matplotlib.pyplot as plt
import csv
import os

if len(sys.argv) < 4 or not sys.argv[1] in ['points', 'result']:
  print "Usage: plot-clusters.py (points|result) <src-file> <pdf-file-prefix>"
  sys.exit(1)

inFile = sys.argv[1]
inFile = sys.argv[2]
outFilePx = sys.argv[3]

inFileName = os.path.splitext(os.path.basename(inFile))[0]
outFile = os.path.join(".", outFilePx+"-plot.pdf")

########### READ DATA

cs = []
xs = []
ys = []

minX = None
maxX = None
minY = None
maxY = None

if sys.argv[1] == 'points':

  with open(inFile, 'rb') as file:
    for line in file:
      # parse data
      csvData = line.strip().split(' ')

      x = float(csvData[0])
      y = float(csvData[1])

      if not minX or minX > x:
        minX = x
      if not maxX or maxX < x:
        maxX = x
      if not minY or minY > y:
        minY = y
      if not maxY or maxY < y:
        maxY = y

      xs.append(x)
      ys.append(y)

    # plot data
    plt.clf()
    plt.scatter(xs, ys, s=25, c="#999999", edgecolors='None', alpha=1.0)
    plt.ylim([minY,maxY])
    plt.xlim([minX,maxX])

elif sys.argv[1] == 'result':

  with open(inFile, 'rb') as file:
    for line in file:
      # parse data
      csvData = line.strip().split(',')

      c = int(csvData[0])
      x = float(csvData[1])
      y = float(csvData[2])

      cs.append(c)
      xs.append(x)
      ys.append(y)

    # plot data
    plt.clf()
    plt.scatter(xs, ys, s=25, c=cs, edgecolors='None', alpha=1.0)
    plt.ylim([minY,maxY])
    plt.xlim([minX,maxX])


plt.savefig(outFile, dpi=600)
print "\nPlotted file: %s" % outFile

sys.exit(0)
```

**Comment by rmetzger** [comment]
@Alex: is the new python script able to handle the output of the `eu.stratosphere.example.java.clustering.util.KMeansDataGenerator` class? I'm getting this error

```
python2.7 plotPoints.py points input
Traceback (most recent call last):
  File "plotPoints.py", line 36, in <module>
    p = int(csvData[0])
ValueError: invalid literal for int() with base 10: '-9.53 -46.26'
```

I'm also getting an error in the web client with the KMeans example:

```
eu.stratosphere.client.program.ProgramInvocationException: The program plan could not be fetched. The program silently swallowed the control flow exceptions.
    at eu.stratosphere.client.program.Client.getOptimizedPlan(Client.java:154)
    at eu.stratosphere.client.web.JobSubmissionServlet.doGet(JobSubmissionServlet.java:161)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:532)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:965)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:388)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:187)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:901)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:425)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:489)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by rmetzger** [comment]
Thank you @aalexandrov. I will update the python script on the website.
