### ISSUE TITLE
Using another drive C:/D: other than where the stratosphere distribution is, results in file not found

### ISSUE THREAD

**Issue by tobwiens** [stratosphere/stratosphere#881]
I tried to slow down the wordcount example by using a slow sdcard as input, to "watch" stratosphere reading the input splits. I checked other partitions and drives and found that it only works with my drive D:. The stratosphere runtime is located on D:.

Command:

```
D:\stratosphereWorkEnvironment\workspace\stratosphere\stratosphere-dist\target\stratosphere-dist-0.5-SNAPSHOT-bin\strato
sphere-0.5-SNAPSHOT\bin>java -Xmx512m -cp "D:\stratosphereWorkEnvironment\workspace\stratosphere\stratosphere-dist\targe
t\stratosphere-dist-0.5-SNAPSHOT-bin\stratosphere-0.5-SNAPSHOT\bin\..\lib\*" eu.stratosphere.client.CliFrontend run --ja
rfile D:/stratosphereWorkEnvironment/workspace/stratosphere/stratosphere-dist/target/stratosphere-dist-0.5-SNAPSHOT-bin/
stratosphere-0.5-SNAPSHOT/examples/stratosphere-scala-examples-0.5-SNAPSHOT-WordCount.jar --arguments 10 file://G:/hamle
t.txt file://D:/stratosphereWorkEnvironment/testdata/wordcount/wordcount-result.txt -v -w
```

Exceptions:

```
14/05/28 17:33:27 WARN io.DelimitedInputFormat: Could not determine statistics for file 'file://G:/hamlet.txt' due to an
 io error: File file://G:/hamlet.txt does not exist.
14/05/28 17:33:27 ERROR client.JobClient: ERROR: eu.stratosphere.nephele.executiongraph.GraphConversionException: Cannot
 compute input splits for CHAIN DataSource(File file://G:/hamlet.txt) -> Map (<Unnamed Mapper>): java.io.FileNotFoundExc
eption: File file://G:/hamlet.txt does not exist.
        at eu.stratosphere.core.fs.local.LocalFileSystem.getFileStatus(LocalFileSystem.java:100)
        at eu.stratosphere.api.common.io.FileInputFormat.createInputSplits(FileInputFormat.java:410)
        at eu.stratosphere.api.common.io.FileInputFormat.createInputSplits(FileInputFormat.java:70)
        at eu.stratosphere.pact.runtime.task.DataSourceTask.computeInputSplits(DataSourceTask.java:332)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:552)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:273)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:174)
        at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:503)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
        at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:951)

        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:555)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:273)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:174)
        at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:503)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
        at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:951)

Error: The program execution failed: eu.stratosphere.nephele.executiongraph.GraphConversionException: Cannot compute inp
ut splits for CHAIN DataSource(File file://G:/hamlet.txt) -> Map (<Unnamed Mapper>): java.io.FileNotFoundException: File
 file://G:/hamlet.txt does not exist.
        at eu.stratosphere.core.fs.local.LocalFileSystem.getFileStatus(LocalFileSystem.java:100)
        at eu.stratosphere.api.common.io.FileInputFormat.createInputSplits(FileInputFormat.java:410)
        at eu.stratosphere.api.common.io.FileInputFormat.createInputSplits(FileInputFormat.java:70)
        at eu.stratosphere.pact.runtime.task.DataSourceTask.computeInputSplits(DataSourceTask.java:332)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:552)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:273)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:174)
        at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:503)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
        at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:951)

        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:555)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:273)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:174)
        at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:503)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
        at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:951)

eu.stratosphere.client.program.ProgramInvocationException: The program execution failed: eu.stratosphere.nephele.executi
ongraph.GraphConversionException: Cannot compute input splits for CHAIN DataSource(File file://G:/hamlet.txt) -> Map (<U
nnamed Mapper>): java.io.FileNotFoundException: File file://G:/hamlet.txt does not exist.
        at eu.stratosphere.core.fs.local.LocalFileSystem.getFileStatus(LocalFileSystem.java:100)
        at eu.stratosphere.api.common.io.FileInputFormat.createInputSplits(FileInputFormat.java:410)
        at eu.stratosphere.api.common.io.FileInputFormat.createInputSplits(FileInputFormat.java:70)
        at eu.stratosphere.pact.runtime.task.DataSourceTask.computeInputSplits(DataSourceTask.java:332)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:552)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:273)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:174)
        at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:503)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
        at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:951)

        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:555)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:273)
        at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:174)
        at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:503)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
        at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:951)

        at eu.stratosphere.client.program.Client.run(Client.java:237)
        at eu.stratosphere.client.program.Client.run(Client.java:203)
        at eu.stratosphere.client.program.Client.run(Client.java:197)
        at eu.stratosphere.client.program.Client.run(Client.java:165)
        at eu.stratosphere.client.CliFrontend.run(CliFrontend.java:337)
        at eu.stratosphere.client.CliFrontend.parseParameters(CliFrontend.java:852)
        at eu.stratosphere.client.CliFrontend.main(CliFrontend.java:878)
```

**Comment by tobwiens** [comment]
When stratosphere is copied to G: and started there (start-local.bat) it can access all files on G:, but no other drive.

**Comment by StephanEwen** [comment]
Can you debug the class 'LocalFilesystem' and see where the error happens?
I think a good place to start is the 'Filesystem.get()' method.

**Comment by zentol** [comment]
you need another `/` in the file scheme.

this worked for me:

```
DataSet<String> points = env.readTextFile("file:///F:/test.txt");
```

this didnt:

```
DataSet<String> points = env.readTextFile("file://F:/test.txt");
```

**Comment by zentol** [comment]
the reason it worked when on the same drive is the following:
 because due to the missing `/` the resulting path is `/test.txt`, for which the current drive letter is automatically added.

**Comment by zentol** [comment]
The source of this occurrence is btw. the URI class:

```
URI t = new URI("file://G:/test.txt");
System.out.println(t.getScheme());
System.out.println(t.getPath());
```

prints

```
file
/test.txt
```

**Comment by tobwiens** [comment]
That's exactly it. Another / has to be added when the file sits on another drive relative to stratosphere. 

It feels very confusing that, depending on where stratopshere runs the absolute file path need to be changed. 

The tripple notation "file:///" does also work if the file is on the same drive.

**Comment by zentol** [comment]
you look at it the wrong way. 
`file:///` is the standard notation for windows systems afaik. 
`file://F:/test.txt` working is more or less a coincidence.
`file:///test.txt` behaves the same way as `file://F:/test.txt`

in short, `file://` is straight up wrong.

**Comment by zentol** [comment]
`It feels very confusing that, depending on where stratopshere runs the absolute file path need to be changed.`

assigning the letter automatically prevents this for some cases. if you have a txt file inside the stratosphere distribution, and know that the top folder is the same on every node, you can specify `file:///<path-without-drive-letter>` and be sure that it runs on any machine, independent of the arbitrary drive letter.
