### ISSUE TITLE
Webclient does not show System.out messages

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#900]
When submitting the KMeans Job using the web client, I'm getting the following exception:

```
An error occurred while invoking the program:

The program plan could not be fetched. The program silently swallowed the control flow exceptions.


eu.stratosphere.client.program.ProgramInvocationException: The program plan could not be fetched. The program silently swallowed the control flow exceptions.
    at eu.stratosphere.client.program.Client.getOptimizedPlan(Client.java:154)
    at eu.stratosphere.client.web.JobSubmissionServlet.doGet(JobSubmissionServlet.java:161)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:532)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:965)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:388)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:187)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:901)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:352)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:425)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:489)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:744)
```

The problem is that the main() method just returns (printing a message to `System.out`).
This is not very intuitive, since you have to look into the webclient.out log

**Comment by StephanEwen** [comment]
Yes. This is somehow a fundamental problem with "interactive" style
programs.

We could temporarily redirect stdout and stderr to display the output in
the web Client.
