### ISSUE TITLE
Using broadcast variables in UDFs within iterations leads to CompilerException

### ISSUE THREAD

**Issue by powibol** [stratosphere/stratosphere#905]
While working with the new Java API I discovered the following behaviour, which I consider to be a bug.

``` java
IterativeDataSet<Theta> iteration = theta.iterate(maxIterations);

DataSet<Gradient> gradient = iteration.crossWithHuge(pointsWithLabels).with(new CrossFunction<Theta, Point, Gradient>() {
    @Override
        public Gradient cross(Theta theta, Point pointWithLabel) throws Exception { return ... }
})
.withBroadcastSet(numberOfPoints, "numberOfPoints")
.withParameters(config);
```

``` java
Exception in thread "main" eu.stratosphere.compiler.CompilerException: No plan meeting the requirements could be created @ Cross (de.tu_berlin.impro3.stratosphere.classification.logreg.LogisticRegression$4) (1:null)(2:null). Most likely reason: Too restrictive plan hints.
    at eu.stratosphere.compiler.dag.OptimizerNode.prunePlanAlternatives(OptimizerNode.java:755)
    at eu.stratosphere.compiler.dag.TwoInputNode.getAlternativePlans(TwoInputNode.java:480)
    at eu.stratosphere.compiler.dag.SingleInputNode.getAlternativePlans(SingleInputNode.java:251)
    at eu.stratosphere.compiler.dag.SingleInputNode.getAlternativePlans(SingleInputNode.java:251)
    at eu.stratosphere.compiler.dag.BulkIterationNode.instantiateCandidate(BulkIterationNode.java:289)
    at eu.stratosphere.compiler.dag.SingleInputNode.addLocalCandidates(SingleInputNode.java:373)
    at eu.stratosphere.compiler.dag.SingleInputNode.getAlternativePlans(SingleInputNode.java:316)
    at eu.stratosphere.compiler.dag.DataSinkNode.getAlternativePlans(DataSinkNode.java:192)
    at eu.stratosphere.compiler.PactCompiler.compile(PactCompiler.java:715)
    at eu.stratosphere.compiler.PactCompiler.compile(PactCompiler.java:553)
    at eu.stratosphere.client.LocalExecutor.executePlan(LocalExecutor.java:216)
    at eu.stratosphere.api.java.LocalEnvironment.execute(LocalEnvironment.java:57)
    at de.tu_berlin.impro3.stratosphere.classification.logreg.LogisticRegression.main(LogisticRegression.java:236)
```

**Comment by rmetzger** [comment]
Thank you for reporting the issue.
It has already been reported here: https://github.com/stratosphere/stratosphere/issues/880.

**Comment by rmetzger** [comment]
What version of Stratosphere have you been using?

**Comment by StephanEwen** [comment]
There has been a recent patch that addressed a similar issue. It is
available in the versions "0.6-SNAPSHOT" and "0.5.1-SNAPSHOT".

Can you try whether that solves your problem?

**Comment by StephanEwen** [comment]
Any news on this issue?

**Comment by powibol** [comment]
I will test it with the new snapshot, but it's not done by now because of the incredibly good weather and an exam next week. :/
I'll report the results of the test soon!

**Comment by StephanEwen** [comment]
Fair enough ;-)

**Comment by powibol** [comment]
Using the new snapshot solved the described problem.
Thank you for your assistance!
