### ISSUE TITLE
Error when compiling from the source

### ISSUE THREAD

**Issue by wilsoncao** [stratosphere/stratosphere#906]
I use the "git clone https://github.com/stratosphere/stratosphere.git" command, and then I use "mvn clean package -DskipTests" to compile but it goes wrong. My java compiler version is javac 1.7.0_55.  The error message is follow:

[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ stratosphere-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 209 source files to /Users/wilsoncao/Documents/stratosphere/stratosphere-java/target/classes
?????? (1.6.0_65) ?г????쳣?? ????? Bug Parade ??û???ҵ??ô??????? Java Developer Connection (http://java.sun.com/webapps/bugreport)  ?Ըô?????й鵵?? ???ڱ????и??????ĳ?????????????Ϣ??лл???ĺ?????
java.lang.NullPointerException
    at com.sun.tools.javac.comp.Check.checkCompatibleConcretes(Check.java:1213)
    at com.sun.tools.javac.comp.Check.checkCompatibleSupertypes(Check.java:1567)
    at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:2674)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2628)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2584)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2584)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2584)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2564)
    at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1045)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:768)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:730)
    at com.sun.tools.javac.main.Main.compile(Main.java:353)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:115)
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] An unknown compilation problem occurred

**Comment by rmetzger** [comment]
Are you sure that you are using Java 1.7 ?
Because the exception says something about "1.6.0_65" and the bug you're mentioning here is only known for java 1.6

What is "mvn -version" saying?

**Comment by wilsoncao** [comment]
oh, My fault...., It is java 1.6.
